spring.application.name=agendamento-service

# Banco H2 em memoria
spring.datasource.url=jdbc:h2:mem:agendamentodb;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# Swagger / OpenAPI
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

# Propriedade customizada de exemplo (agendamento.nome-servico)
agendamento.nome-servico=Agendamento Service


